server:
  port: 80

# Ribbon 客户端负载均衡，所需Eureka 配置
eureka:
  client: #客户端注册进eureka服务列表内
    register-with-eureka: false
    service-url: 
      #单机版
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      